permalink: /:path/
collections:
  gallery:
    output: true
    permalink: /:collection/:path/
  projects:
    output: true
    permalink: /:collection/:path/
  members:
    output: true
    permalink: /:collection/:path/
  guides:
    output: true
    permalink: /:collection/:path/
  posts:
    output: true
    permalink: /:collection/:path/

plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from
